### ISSUE TITLE
Add new specs and improve project structure

### ISSUE THREAD

**Issue by rodrigo7491** [informalsystems/apalache-bench#60]
We should add the specs from the [tla-files](https://github.com/informalsystems/tla-files) repo that can be made public to the benchmarking infrastructure. In doing so, we should identify potential pain points and improve the current setup.

- [x] Add specs from the endive artifact: #52.
- [x] Add remaining publicly available specs: #54, #57.
- [x] Improve benchmarking infrastructure: #53, #56, #59.
